spring.application.name=ingestion-service
server.port=8081

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=ingestion-service
spring.kafka.consumer.auto-offset-reset=earliest

management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true